server:
  port: 8090
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**

  datasource:
    url: jdbc:mysql://localhost:3306/zhengxiang
    driverClassName: org.gjt.mm.mysql.Driver
    username: root
    password: root
    dbcp2:
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      num-tests-per-eviction-run: 50
      soft-min-evictable-idle-time-millis: 3600000
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:E:/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo1.model

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql






